services:
  - type: web
    name: whop-webhook-server
    runtime: node
    buildCommand: npm install
    startCommand: node preview-server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
